#!/usr/bin/env python
import os
import os.path
import commands

cmd = raw_input("command > ")

try:
    if cmd == 'ls' :
        os.system("dir")    
    else:
        os.system(cmd)
except:    
    print "command > invalid"
